---
baseURL: https://callvoiptelefoniewebsite.netlify.com
LanguageCode: nl
title: Callvoip
theme: callvoiptelefonie
enableRobotsTXT: true
MetaDataFormat: yaml
params:
  cloudinary_base_url: https://res.cloudinary.com/callvoip/image/upload
taxonomies:
  category: categories
  onderdeel: onderdelen
  tag: tags
menu:
  top:
  - pre: external
    url: https://status.kwebbl.com/
    name: Status
    weight: 1
  - pre: external
    url: https://callvoip.shop/
    name: Webshop
    weight: 4
  - pre: external
    url: https://panel.callvoip.nl/login/panel
    name: Login
    weight: 5
  - url: "/ondersteuning"
    name: Ondersteuning
    weight: 2
  footer:
  - url: https://www.callvoip.nl/download/callvoip/CallVoip_telefonie_aanvraagformulier.pdf
    name: Direct klant worden?
    weight: 4
outputs:
  home:
  - HTML
  - JSON
