baseURL: "https://callvoiptelefoniewebsite.netlify.com"
languageCode: "en-us"
title: "callvoiptelefonie"
theme: "callvoiptelefonie"
params:
  cloudinary_base_url: "https://res.cloudinary.com/spinme/image/upload"
# menu:
#   main
