backend:
  name: git-gateway
  branch: master
  repo: Tijdhof/callvoip-website

media_folder: "static/blogimg" # Folder where user uploaded files should go
public_folder: "blogimg"

media_library:
  name: cloudinary
  config:
    cloud_name: callvoip
    api_key: 755977546423949

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/nieuws'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Type", name: "type", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Images", name: "images", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}], required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Hide in search", name: "hideinsearch", widget: "boolean", default: false}
      - {label: "Hide in Google", name: "hideingoogle", widget: "boolean", default: false}
      - {label: "Hide social share", name: "hidesocialshare", widget: "boolean", default: false}
      - {label: "Image uitgelicht", name: "image_uitgelicht", widget: "image", required: false}
      - label: "Hero"
        name: "hero"
        widget: "object"
        required: false
        fields: 
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Mobile", name: "mobile", widget: "image", required: false}
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Disable image on mobile", name: "disable_image_on_mobile", widget: "boolean", default: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Contactpersoon", name: "contactpersoon", widget: "relation", collection: "contactpersoon", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - {label: "Categories", name: "categories", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - {label: "Tags", name: "tags", widget: "relation", collection: "tags", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "single_pages"
    label: "Single Pages"
    files: 
      - label: Status
        name: "status"
        file: content/status/_index.md
        fields:
          - {label: "Title", name: "title", widget: "string",default: "Status"}
          - {label: "Aliases", name: "alias", widget: "string",default: "/storing"}
          - {label: "URL", name: "url", widget: "string",default: "/status"}
          - {label: "Content Top", name: "contentTop", widget: "string"}
          - {label: "Content Middle", name: "contentMiddle", widget: "string"}
          - {label: "Hide social share", name: "hidesocialshare", widget: "boolean", default: false}
          - label: "Hero"
            name: "hero" 
            widget: "object"
            fields: 
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Disable image on mobile", name: "disable_image_on_mobile", widget: "boolean", default: false}
          - label: "Items"
            name: "items"
            widget: "list"
            summary: '{{fields.title}} - {{fields.status}}'
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Status", name: "status", widget: "boolean", default: false}
          - label: "Tests"
            name: "tests"
            widget: "list"
            summary: '{{fields.title}} - {{fields.error}}'
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Error", name: "error", widget: "boolean", default: false, required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}